// Regenerates tests/browser-harness.html by inlining the current
// dist/loafing-reader.user.js into the harness template.
// Usage: node scripts/make-harness.js
'use strict';
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const dist = fs.readFileSync(path.join(ROOT, 'dist', 'loafing-reader.user.js'), 'utf8')
    .replace(/^\/\/ ==UserScript==.*?\/\/ ==\/UserScript==\r?\n/s, '');

const harnessPath = path.join(ROOT, 'tests', 'browser-harness.html');
const harness = fs.readFileSync(harnessPath, 'utf8');

// Replace the contents of the second <script> block (the inlined bundle).
// Line endings may be LF or CRLF, so match flexibly.
const beginMatch = /<script>\r?\n\/\/ BEGIN_INLINE_BUNDLE/.exec(harness);
if (!beginMatch) {
    console.error('harness marker not found — is tests/browser-harness.html intact?');
    process.exit(1);
}
const scriptStart = beginMatch.index + beginMatch[0].length;
const endMatch = /\r?\n\/\/ END_INLINE_BUNDLE\r?\n<\/script>/.exec(harness.slice(scriptStart));
if (!endMatch) {
    console.error('end marker not found');
    process.exit(1);
}
const end = scriptStart + endMatch.index;

const out = harness.slice(0, scriptStart)
    + '\n// (bundle regenerated by scripts/make-harness.js — do not edit)\n'
    + dist
    + harness.slice(end);
fs.writeFileSync(harnessPath, out);
console.log('regenerated tests/browser-harness.html');
